version: '3.1'

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: my_postgres_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ryan
      POSTGRES_PASSWORD: ryan
      POSTGRES_DB: tiktokclone
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: 
